version: "3.8"
services:
  json_exporter:
    image: quay.io/prometheuscommunity/json-exporter:v0.5.0
    container_name: json_exporter
    volumes:
      - $PWD/examples/config.yml:/config.yml:ro
    ports:
      - "7979:7979"
  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    volumes:
      - $PWD/examples/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  # Grafana default login is: admin/admin
  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    ports:
      - "3000:3000"
