global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: json_exporter
    scrape_interval: 1m
    scrape_timeout: 30s
    honor_labels: true
    metrics_path: /probe
    static_configs:
      - targets:
          - https://api.coinstats.app/public/v1/coins?currency=USD
          - https://api.coinstats.app/public/v1/coins?currency=EUR
          - https://api.coinstats.app/public/v1/coins?currency=AMD
          - https://api.coinstats.app/public/v1/coins?currency=SEK
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__address__]
        regex: ^http.+currency=([A-Z]{3})
        action: replace
        target_label: currency
        replacement: ${1}
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979